from typing import Dict

from django.http import HttpRequest
from ninja import Router

from ralph.clients.authorization.auth import Authorization

router = Router()


@router.get("/healthcheck")
def healthcheck(request: HttpRequest) -> Dict[str, str]:

    """
    Basic healthcheck endpoint.

    This endpoint function is just to check if API is reachable.

    Args:
        request (HttpRequest): HTTP Request.

    Returns:
        Dict[str, str]: Dictionary containing message informing user that system is
            running correctly.
    """

    return {"message": "System is running."}


@router.get("/login-check", auth=Authorization())
def login_check(request: HttpRequest) -> Dict[str, str]:

    """
    Basic authorization endpoint for token.

    This endpoint function is just to check if authorization is requesting credentials
    generated by logging in to the API.

    Args:
        request (HttpRequest): HTTP Request.

    Returns:
        Dict[str, str]: Dictionary containing message informing user that it has enough
            permission to access endpoint.
    """

    return {"message": "Login passed."}


@router.get("/role-check", auth=Authorization(roles=["role_check"]))
def role_check(request: HttpRequest) -> Dict[str, str]:

    """
    Basic authorization endpoint for role.

    This endpoint function is just to check if authorization is blocking any user that
    is not part of 'role_check' role.

    Args:
        request (HttpRequest): HTTP Request.

    Returns:
        Dict[str, str]: Dictionary containing message informing user that it has enough
            permission to access endpoint.
    """

    return {"message": "Role required passed."}


@router.get("/permission-check", auth=Authorization(permissions=["permission_check"]))
def permission_check(request: HttpRequest) -> Dict[str, str]:

    """
    Basic authorization endpoint for permission.

    This endpoint function is just to check if authorization is blocking any user that
    has not 'permission_check' permission.

    Args:
        request (HttpRequest): HTTP Request.

    Returns:
        Dict[str, str]: Dictionary containing message informing user that it has enough
            permission to access endpoint.
    """

    return {"message": "Permission required passed."}
