from django.http import HttpRequest
from ninja import Router

from ralph.clients.authorization.auth import Authorization

router = Router()


@router.get("/healthcheck")
def healthcheck(request: HttpRequest) -> dict:

    """
    Basic healthcheck endpoint.

    This endpoint function is just to check if API is reachable.
    """

    return {"message": "System is running."}


@router.get("/login-check", auth=Authorization())
def login_check(request: HttpRequest) -> dict:

    """
    Basic authorization endpoint for token.

    This endpoint function is just to check if authorization is requesting credentials
    generated by logging in to the API.
    """

    return {"data": request.auth}


@router.get("/role-check", auth=Authorization(roles=["role_check"]))
def role_check(request: HttpRequest) -> dict:

    """
    Basic authorization endpoint for role.

    This endpoint function is just to check if authorization is blocking any user that
    is not part of 'role_check' role.
    """

    return {"data": request.auth}


@router.get("/permission-check", auth=Authorization(permissions=["permission_check"]))
def permission_check(request: HttpRequest) -> dict:

    """
    Basic authorization endpoint for permission.

    This endpoint function is just to check if authorization is blocking any user that
    has not 'permission_check' permission.
    """

    return {"data": request.auth}
